### PR TITLE
Update page.tsx

### PR DESCRIPTION
**Pull request by hrittm**

### CODE REVIEW

**Comment by MuntasirSZN** [comment]
@hrimondal Run `bun fmt` or `npm run fmt` to solve this errors and commit it.

**Comment by hrittm** [comment]
> @hrimondal Run `bun fmt` or `npm run fmt` to solve this errors and commit it.

I commited from web
Not from terminal

**Comment by MuntasirSZN** [comment]
> > @hrimondal Run `bun fmt` or `npm run fmt` to solve this errors and commit it.
> 
> I commited from web Not from terminal

IDK But You need To Run that Or This PR Will Be Closed.

**Comment by MuntasirSZN** [comment]
@hrimondal Nah I Did It, R.I.P

**Review by MuntasirSZN — APPROVED** [review]

**Pull request merged**
